### ISSUE TITLE
Renaming leads to crash

### ISSUE THREAD

**Issue by TLINDEN** [MightyMoud/sidekick#32]
First of all I want to thank you @MightyMoud for the effort you put into this project!

I started an app on my vps and entered my own domain name. But then I changed my mind, edited `sidekick.yml` and gave it a name under the `sslip.io` domain.

This is the result when I re-deployed:

```default
sidekick deploy 

Deploying a new version of your app 😏                                                              

 SUCCESS  Logged in successfully!
 SUCCESS  Latest docker image built
▀  Deploying a new version of your application
panic: error running command -                                                  
        cd up && \                                                              
        old_container_id=$(docker ps -f name=up -q | tail -n1) && \  
        docker compose -p sidekick up -d --no-deps --scale up=2 --no-recreate up && \
        new_container_id=$(docker ps -f name=up -q | head -n1) && \
        new_container_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $new_container_id) && \
        curl --silent --include --retry-connrefused --retry 30 --retry-delay 1 --fail http://$new_container_ip:8888/ || exit 1 && \
        docker stop $old_container_id && \          
        docker rm $old_container_id && \                
        docker compose -p sidekick up -d --no-deps --scale up=1 --no-recreate up 
        : - time="2024-09-30T11:30:46Z" level=warning msg="Found orphan containers ([sidekick-traefik-service-1]) for this project. If you removed or renamed thi
s service in your compose file, you can run this command with the --remove-orphans flag to clean it up."

goroutine 1 [running]:
github.com/mightymoud/sidekick/cmd.init.func2(0xc0001d8900?, {0x85623d?, 0x4?, 0x856241?})
        /Users/msmo/Projects/sidekick/cmd/deploy.go:131 +0x1c45
github.com/spf13/cobra.(*Command).execute(0xc1ef40, {0xc864a0, 0x0, 0x0})
        /Users/msmo/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc1fda0)
        /Users/msmo/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/msmo/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/mightymoud/sidekick/cmd.Execute()
        /Users/msmo/Projects/sidekick/cmd/root.go:33 +0x1a
main.main()
        /Users/msmo/Projects/sidekick/main.go:20 +0xf
```

Well, I could just throw the vps away and start from scratch. But it would be a good thing to be able to modify an existing deployment somehow.

**Comment by MightyMoud** [comment]
Hey @TLINDEN,

Thanks for your kind words. ❤️

Yeah that won't work right now. I do think it should though. So I'll work on it at some point soon. 

Lots of other low hanging fruits I want to catch first before I work on that level of polish. 

Cheers

**Comment by MightyMoud** [comment]
I will work on modifying existing deployment at some point in the future for now, I'll close this.
